### PR TITLE
Update and merge tools

### PR DESCRIPTION
**Pull request by opsecx**
Updated link in my votes checker. Added my transactions analyzer (not an explorer).

### CODE REVIEW

**Comment by RuslanGlaznyov** [comment]
@opsecx 
Thanks for your valuable contribution! I see that your tools have open-source code. Could you please add an open_source tag for projects and attach a link to GitHub? 
here is example 
https://github.com/MELLIFERA-Labs/namada-awesome/edit/main/Tools/Namada%20Self%20Host.md

**Comment by opsecx** [comment]
Will do!

**Comment by opsecx** [comment]
Alright I updated in my branch. I think the updates have been included in this PR but not 100, I'm a little new to github. Lmk if I need to close this PR and add a new instead!

**Comment by RuslanGlaznyov** [comment]
LGTM!

**Pull request merged**
